package client.maplepal;

public enum MaplePalRes {
	RES_PAL_WINDOW_DETAIL,
	RES_PAL_WINDOW_MOVE_TO_STORAGE,
	RES_PAL_WINDOW_MOVE_TO_ACTIVE,
	RES_PAL_WINDOW_RECYCLE_SUCCESSFUL,
	RES_PAL_WINDOW_SET_ACTIVE_LEVELING,
	RES_PAL_HATCH_BEGIN,
	RES_PAL_HATCH_CANCEL,
	RES_PAL_HATCH_COMPLETE,
	RES_PAL_ERROR,
}
