package client.maplepal;

public enum MaplePalReq {
	REQ_PAL_WINDOW_DETAIL,
	REQ_PAL_WINDOW_STORAGE_TO_ACTIVE,
	REQ_PAL_WINDOW_ACTIVE_TO_STORAGE,
	REQ_PAL_WINDOW_RECYCLE,
	REQ_PAL_WINDOW_SET_ACTIVE_LEVELING,
	REQ_PAL_HATCH_BEGIN,
	REQ_PAL_HATCH_CANCEL,
	REQ_PAL_HATCH_COMPLETE,
}
